default:
  image: ubuntu:20.04

stages:
  - deploy
  - test

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
    - public/
  only:
  - master

show:
  stage: test
  script:
    - echo "show pages"


