# Site settings
title:          远道的博客
description:    "Rain is a simple and clean Jekyll theme with focus on content."
url:           https://github.com/Yuandao4621/yuandao4621.github.io

# Author
author:
  name:         远道
  email:        yuandao4621@outlook.com
  # url:          https://inelaah.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: yuandao4621@outlook.com
  jianshu: https://www.jianshu.com/u/c68fc45881f2
  github: https://github.com/Yuandao4621/yuandao4621.github.io
  twitter: https://twitter.com
  linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
